apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm/nginx-deployment-helm-config
    repoURL: https://github.com/abhilashkkale/python-flask-hello-world-github-ci
    targetRevision: HEAD
